-- MySQL Script generated by MySQL Workbench
-- Wed Oct  3 18:00:52 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`ProfileMaster`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ProfileMaster` (
  `userId` VARCHAR(45) NOT NULL,
  `gender` INT NOT NULL,
  `intrestedIn` VARCHAR(45) NOT NULL,
  `my_neighbourhood` VARCHAR(45) NOT NULL,
  `height` VARCHAR(45) NOT NULL,
  `college` VARCHAR(45) NOT NULL,
  `level_of_education` VARCHAR(45) NOT NULL,
  `current_job` VARCHAR(45) NOT NULL,
  `age_prefrence` VARCHAR(45) NOT NULL,
  `occupation` VARCHAR(45) NOT NULL,
  `religion` VARCHAR(45) NOT NULL,
  `age_pref` VARCHAR(45) NOT NULL,
  `venue` VARCHAR(45) NOT NULL,
  `connection` VARCHAR(45) NOT NULL,
  `type_of_scene` VARCHAR(45) NOT NULL,
  `img_url1` VARCHAR(45) NULL,
  `img_url2` VARCHAR(45) NULL,
  `img_url3` VARCHAR(45) NULL,
  `profile_pic_url` VARCHAR(45) NULL,
  PRIMARY KEY (`userId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ReviewMaster`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ReviewMaster` (
  `reviewId` VARCHAR(45) NOT NULL,
  `userId` VARCHAR(45) NOT NULL,
  `review` VARCHAR(45) NOT NULL,
  `review_star` VARCHAR(45) NOT NULL,
  `review_by` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`userId`, `reviewId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`VenueMaster`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`VenueMaster` (
  `venueId` VARCHAR(45) NOT NULL,
  `venue_name` VARCHAR(45) NOT NULL,
  `venue_address` VARCHAR(45) NOT NULL,
  `venue_manager_name` VARCHAR(45) NOT NULL,
  `venue_contact_number` VARCHAR(45) NOT NULL,
  `venue_url` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`venueId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`HexInfoMaster`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`HexInfoMaster` (
  `hexId` VARCHAR(45) NOT NULL,
  `hex_venue_id` VARCHAR(45) NOT NULL,
  `isConfirmed` VARCHAR(45) NOT NULL,
  `isPaymentDone` VARCHAR(45) NOT NULL,
  `hex_created_date` VARCHAR(45) NOT NULL,
  `hext_date` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`hexId`, `hex_venue_id`),
  INDEX `venueKey_idx` (`hex_venue_id` ASC) VISIBLE,
  CONSTRAINT `venueKey`
    FOREIGN KEY (`hex_venue_id`)
    REFERENCES `mydb`.`VenueMaster` (`venueId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PaymentMaster`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PaymentMaster` (
  `paymentId` VARCHAR(45) NOT NULL,
  `userId` VARCHAR(45) NOT NULL,
  `HexId` VARCHAR(45) NOT NULL,
  `amount_paid` VARCHAR(45) NOT NULL,
  `payment_status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`HexId`, `userId`, `paymentId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`InviteMaster`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`InviteMaster` (
  `userId` VARCHAR(45) NOT NULL,
  `invite_userId` VARCHAR(45) NOT NULL,
  `hexId` VARCHAR(45) NOT NULL,
  `Invite_date` VARCHAR(45) NOT NULL,
  `Invite_status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`hexId`, `userId`, `invite_userId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`HexMaster`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`HexMaster` (
  `hexId` VARCHAR(45) NOT NULL,
  `hex_createdBy` VARCHAR(45) NOT NULL,
  `match_userId2` VARCHAR(45) NOT NULL,
  `match_userId3` VARCHAR(45) NOT NULL,
  `opp_userId1` VARCHAR(45) NOT NULL,
  `opp_userId2` VARCHAR(45) NOT NULL,
  `opp_userId3` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`hexId`, `hex_createdBy`),
  INDEX `paymentUserKey_idx` (`hex_createdBy` ASC) VISIBLE,
  CONSTRAINT `hexIdKey`
    FOREIGN KEY (`hexId`)
    REFERENCES `mydb`.`HexInfoMaster` (`hexId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `paymentHexKey`
    FOREIGN KEY (`hexId`)
    REFERENCES `mydb`.`PaymentMaster` (`HexId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `InviteId`
    FOREIGN KEY ()
    REFERENCES `mydb`.`InviteMaster` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `invitedHexId`
    FOREIGN KEY (`hexId`)
    REFERENCES `mydb`.`InviteMaster` (`hexId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `paymentUserKey`
    FOREIGN KEY (`hex_createdBy`)
    REFERENCES `mydb`.`PaymentMaster` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`userMaster`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`userMaster` (
  `userid` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(16) NOT NULL,
  `last_name` VARCHAR(45) NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `mobile` VARCHAR(45) NOT NULL,
  `created_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `category_type` VARCHAR(45) NOT NULL,
  `isActive` VARCHAR(45) NULL,
  `isInvited` VARCHAR(45) NULL,
  `invited_id` VARCHAR(45) NULL,
  `review_time` VARCHAR(45) NULL,
  `category_type` VARCHAR(45) NULL,
  PRIMARY KEY (`userid`),
  CONSTRAINT `UserDetailsKey`
    FOREIGN KEY (`userid`)
    REFERENCES `mydb`.`ProfileMaster` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `UserIdReviewKey`
    FOREIGN KEY (`userid`)
    REFERENCES `mydb`.`ReviewMaster` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `HexCreatedBy`
    FOREIGN KEY (`userid`)
    REFERENCES `mydb`.`HexMaster` (`hex_createdBy`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`LoginMaster`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`LoginMaster` (
  `userId` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `facebookId` VARCHAR(45) NULL,
  `device_type` VARCHAR(45) NULL,
  `device_token` VARCHAR(45) NULL,
  PRIMARY KEY (`userId`),
  CONSTRAINT `userDetails`
    FOREIGN KEY (`userId`)
    REFERENCES `mydb`.`userMaster` (`userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
